apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-min-side-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-proxy/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-proxy/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.nav.no/tms-min-side-proxy"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
    outbound:
      external:
        - host: syfomotebehov.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: tms-mikrofrontend-selector
        - application: logging
          namespace: nais-system
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: www.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: PERSONALIA_BASE_URL
      value: http://tms-personalia-api/tms-personalia-api
    - name: PERSONALIA_CLIENT_ID
      value: prod-gcp:min-side:tms-personalia-api
    - name: SELCTOR_BASE_URL
      value: http://tms-mikrofrontend-selector
    - name: SELCTOR_CLIENT_ID
      value: prod-gcp:min-side:tms-mikrofrontend-selector
    - name: PDL_API_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_API_CLIENT_ID
      value: "prod-fss:pdl:pdl-api"
    - name: PDL_BEHANDLINGSNUMMER
      value: "B328"
