apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-proxy-secrets
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.nav.no"
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-min-side-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-proxy/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses:
    - "https://www.nav.no/tms-min-side-proxy"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: tms-utkast
        - application: tms-personalia-api
        - application: tms-mikrofrontend-selector
        - application: meldekort-api
          namespace: meldekort
        - application: soknad-api
          namespace: aap
