apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-min-side-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-proxy/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-proxy/metrics
  replicas:
    min: 2
    max: 4
  secureLogs:
    enabled: true
  ingresses:
    - "https://www.dev.nav.no/tms-min-side-proxy"
    - "https://www.intern.dev.nav.no/tms-min-side-proxy"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: https://veilarboppfolging.dev-fss-pub.nais.io
      rules:
        - application: tms-utkast
        - application: dittnav-event-aggregator
        - application: tms-statistikk
        - application: tms-personalia-api
        - application: tms-mikrofrontend-selector
        - application: tms-varsel-api
        - application: meldekort-api-q2
          namespace: meldekort
        - application: soknad-api
          namespace: aap
        - application: isdialogmote
          namespace: teamsykefravr
        - application: veilarboppfolging
          namespace: pto
          cluster: dev-fss
        - application: aia-backend
          namespace: paw
          cluster: dev-gcp
  env:

    - name: CORS_ALLOWED_ORIGINS
      value: "*.dev.nav.no"
    - name: MELDEKORT_APPLICATION
      value: "meldekort-api-q2"
    - name: OPPFOLGING_API_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io/veilarboppfolging
    - name: OPPFOLGING_CLIENT_ID
      value: dev-fss:pto:veilarboppfolging
