apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-proxy-secrets
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-min-side-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-proxy/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-proxy/metrics
  replicas:
    min: 2
    max: 4
  secureLogs:
    enabled: true
  webproxy: true
  ingresses:
    - "https://www.dev.nav.no/tms-min-side-proxy"
    - "https://www.intern.dev.nav.no/tms-min-side-proxy"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: tms-utkast
        - application: dittnav-event-aggregator
        - application: tms-statistikk
        - application: tms-personalia-api
        - application: tms-mikrofrontend-selector
        - application: tms-varsel-api
        - application: meldekort-api-q2
          namespace: meldekort
        - application: soknad-api
          namespace: aap
  env:
    - name: STATISTIKK_BASE_URL
      value: http://tms-statistikk
    - name: STATISTIKK_CLIENT_ID
      value: dev-gcp.min-side.tms-statistikk
    - name: AAP_BASE_URL
      value: http://soknad-api.aap
    - name: AAP_CLIENT_ID
      value: dev-gcp:aap:soknad-api
    - name: CORS_ALLOWED_ORIGINS
      value: "*.dev.nav.no"
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: EVENT_AGGREGATOR_BASE_URL
      value: http://dittnav-event-aggregator
    - name: EVENT_AGGREGATOR_CLIENT_ID
      value: dev-gcp:min-side:dittnav-event-aggregator
    - name: MELDEKORT_BASE_URL
      value: http://meldekort-api-q2.meldekort/meldekort/meldekort-api
    - name: MELDEKORT_CLIENT_ID
      value: dev-gcp:meldekort:meldekort-api-q2
    - name: PERSONALIA_BASE_URL
      value: http://tms-personalia-api/tms-personalia-api
    - name: PERSONALIA_CLIENT_ID
      value: dev-gcp:min-side:tms-personalia-api
    - name: SELCTOR_BASE_URL
      value: http://tms-mikrofrontend-selector
    - name: SELCTOR_CLIENT_ID
      value: dev-gcp:min-side:tms-mikrofrontend-selector
    - name: UTKAST_BASE_URL
      value: http://tms-utkast
    - name: UTKAST_CLIENT_ID
      value: dev-gcp:min-side:tms-utkast
    - name: VARSEL_BASE_URL
      value: http://tms-varsel-api
    - name: VARSEL_CLIENT_ID
      value: dev-gcp:min-side:tms-varsel-api


