apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-proxy-secrets
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-min-side-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-proxy/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-proxy/metrics
  replicas:
    min: 2
    max: 4
  secureLogs:
    enabled: true
  webproxy: true
  ingresses:
    - "https://www.dev.nav.no/tms-min-side-proxy"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: tms-utkast
        - application: dittnav-event-aggregator
        - application: tms-statistikk
        - application: tms-personalia-api
        - application: tms-mikrofrontend-selector
        - application: tms-varsel-api
        - application: meldekort-api-q2
          namespace: meldekort
        - application: soknad-api
          namespace: aap
  env:
    - name: STATISTIKK_BASE_URL
      value: "http://tms-statistikk"
    - name: STATISTIKK_CLIENT_ID
      value: "dev-gcp:min-side:tms-statistikk"


